spring:
  application:
    name: mcp-oauth-server
  security:
    oauth2:
      authorizationserver:
        client:
          mcp-client:
            registration:
              client-id: "client"
              client-secret: "secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080"
                - "https://mcp-chat-client.onrender.com"
              scopes:
                - "openid"
                - "profile"
                - "read"
                - "write"
            require-proof-key: true

server:
  port: 9090

logging.level.org.springframework.security: DEBUG
logging.level.org.springframework.security.oauth2: DEBUG
logging.level.org.springframework.web: DEBUG